services:
    app.kernel_event_handler.request:
        class: App\KernelEvent\EventHandler\RequestEventHandler
        tags: ['app.kernel_event_handler']
        autowire: true
        autoconfigure: true
