api_platform:
    title: 'Wishlist API'
    description: 'An API allowing users to manage their wishlists'
    version: 0.1.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            header_key_auth:
                name: '%api_key_query_param_name%'
                type: 'header'
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
        jsonhal:
            mime_types:
                - application/hal+json
        csv:
            mime_types:
                - text/csv