framework:
    secret: '%env(APP_SECRET)%'
    serializer:
        enable_annotations: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
