security:
    providers:
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        main:
            anonymous: true
            lazy: true
            logout: ~
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\ApiKeyAuthenticator
    access_control:
        - { path: ^[ / ]?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users$, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
