imports:
    - { resource: services/ownership_resolver.yaml }
    - { resource: services/kernel_event_handler.yaml }
    - { resource: services/serializer.yaml }

parameters:
    api_key_query_param_name: key

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $apiKeyQueryParamName: '%api_key_query_param_name%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Serializer'
    App\Serializer\AccessControlNormalizer:
        arguments: [ '@api_platform.serializer.normalizer.item' ]