imports:
    - { resource: services/ownership_resolver.yaml }
    - { resource: services/kernel_event_handler.yaml }
    - { resource: services/serializer.yaml }

parameters:
    api_key_query_param_name: key

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $apiKeyQueryParamName: '%api_key_query_param_name%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Serializer\AccessControlNormalizer:
        arguments: ['@api_platform.jsonld.normalizer.item']